word_database = {
    'level1': [
        {'word': 'apple', 'meaning': '苹果', 'firstLetter': 'a'},
        {'word': 'banana', 'meaning': '香蕉', 'firstLetter': 'b'},
        {'word': 'cat', 'meaning': '猫', 'firstLetter': 'c'},
        {'word': 'dog', 'meaning': '狗', 'firstLetter': 'd'},
        {'word': 'elephant', 'meaning': '大象', 'firstLetter': 'e'},
        {'word': 'fish', 'meaning': '鱼', 'firstLetter': 'f'},
        {'word': 'girl', 'meaning': '女孩', 'firstLetter': 'g'},
        {'word': 'house', 'meaning': '房子', 'firstLetter': 'h'},
        {'word': 'ice', 'meaning': '冰', 'firstLetter': 'i'},
        {'word': 'jump', 'meaning': '跳跃', 'firstLetter': 'j'},
        {'word': 'kite', 'meaning': '风筝', 'firstLetter': 'k'},
        {'word': 'lion', 'meaning': '狮子', 'firstLetter': 'l'},
        {'word': 'monkey', 'meaning': '猴子', 'firstLetter': 'm'},
        {'word': 'nose', 'meaning': '鼻子', 'firstLetter': 'n'},
        {'word': 'orange', 'meaning': '橙子', 'firstLetter': 'o'},
        {'word': 'pig', 'meaning': '猪', 'firstLetter': 'p'},
        {'word': 'queen', 'meaning': '女王', 'firstLetter': 'q'},
        {'word': 'rabbit', 'meaning': '兔子', 'firstLetter': 'r'},
        {'word': 'sun', 'meaning': '太阳', 'firstLetter': 's'},
        {'word': 'tiger', 'meaning': '老虎', 'firstLetter': 't'},
        {'word': 'umbrella', 'meaning': '雨伞', 'firstLetter': 'u'},
        {'word': 'violin', 'meaning': '小提琴', 'firstLetter': 'v'},
        {'word': 'water', 'meaning': '水', 'firstLetter': 'w'},
        {'word': 'yellow', 'meaning': '黄色', 'firstLetter': 'y'},
        {'word': 'zebra', 'meaning': '斑马', 'firstLetter': 'z'}
    ],
    'level2': [
        {'word': 'beautiful', 'meaning': '美丽的', 'firstLetter': 'b'},
        {'word': 'clever', 'meaning': '聪明的', 'firstLetter': 'c'},
        {'word': 'dangerous', 'meaning': '危险的', 'firstLetter': 'd'},
        {'word': 'exciting', 'meaning': '令人兴奋的', 'firstLetter': 'e'},
        {'word': 'fantastic', 'meaning': '极好的', 'firstLetter': 'f'},
        {'word': 'generous', 'meaning': '慷慨的', 'firstLetter': 'g'},
        {'word': 'happy', 'meaning': '快乐的', 'firstLetter': 'h'},
        {'word': 'interesting', 'meaning': '有趣的', 'firstLetter': 'i'},
        {'word': 'kind', 'meaning': '善良的', 'firstLetter': 'k'},
        {'word': 'lovely', 'meaning': '可爱的', 'firstLetter': 'l'},
        {'word': 'magnificent', 'meaning': '壮丽的', 'firstLetter': 'm'},
        {'word': 'nervous', 'meaning': '紧张的', 'firstLetter': 'n'},
        {'word': 'outstanding', 'meaning': '杰出的', 'firstLetter': 'o'},
        {'word': 'patient', 'meaning': '耐心的', 'firstLetter': 'p'},
        {'word': 'quiet', 'meaning': '安静的', 'firstLetter': 'q'},
        {'word': 'responsible', 'meaning': '负责任的', 'firstLetter': 'r'},
        {'word': 'strong', 'meaning': '强壮的', 'firstLetter': 's'},
        {'word': 'talented', 'meaning': '有才华的', 'firstLetter': 't'},
        {'word': 'useful', 'meaning': '有用的', 'firstLetter': 'u'},
        {'word': 'valuable', 'meaning': '有价值的', 'firstLetter': 'v'},
        {'word': 'wonderful', 'meaning': '精彩的', 'firstLetter': 'w'},
        {'word': 'young', 'meaning': '年轻的', 'firstLetter': 'y'},
        {'word': 'zealous', 'meaning': '热情的', 'firstLetter': 'z'}
    ],
    'level3': [
        {'word': 'adventure', 'meaning': '冒险', 'firstLetter': 'a'},
        {'word': 'brilliant', 'meaning': '杰出的', 'firstLetter': 'b'},
        {'word': 'challenge', 'meaning': '挑战', 'firstLetter': 'c'},
        {'word': 'discovery', 'meaning': '发现', 'firstLetter': 'd'},
        {'word': 'education', 'meaning': '教育', 'firstLetter': 'e'},
        {'word': 'friendship', 'meaning': '友谊', 'firstLetter': 'f'},
        {'word': 'government', 'meaning': '政府', 'firstLetter': 'g'},
        {'word': 'happiness', 'meaning': '幸福', 'firstLetter': 'h'},
        {'word': 'imagination', 'meaning': '想象力', 'firstLetter': 'i'},
        {'word': 'knowledge', 'meaning': '知识', 'firstLetter': 'k'},
        {'word': 'language', 'meaning': '语言', 'firstLetter': 'l'},
        {'word': 'memory', 'meaning': '记忆', 'firstLetter': 'm'},
        {'word': 'nature', 'meaning': '自然', 'firstLetter': 'n'},
        {'word': 'opportunity', 'meaning': '机会', 'firstLetter': 'o'},
        {'word': 'philosophy', 'meaning': '哲学', 'firstLetter': 'p'},
        {'word': 'question', 'meaning': '问题', 'firstLetter': 'q'},
        {'word': 'relationship', 'meaning': '关系', 'firstLetter': 'r'},
        {'word': 'science', 'meaning': '科学', 'firstLetter': 's'},
        {'word': 'technology', 'meaning': '技术', 'firstLetter': 't'},
        {'word': 'university', 'meaning': '大学', 'firstLetter': 'u'},
        {'word': 'victory', 'meaning': '胜利', 'firstLetter': 'v'},
        {'word': 'wisdom', 'meaning': '智慧', 'firstLetter': 'w'},
        {'word': 'yesterday', 'meaning': '昨天', 'firstLetter': 'y'},
        {'word': 'zoology', 'meaning': '动物学', 'firstLetter': 'z'}
    ]
}